<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class EmailModelsSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        DB::table('email_models')->insert([
            [
                'id' => 1,
                'name' => "Inscription fournisseur",
                'object' => "Bienvenue",
                'logoUrl' => "https://www.v3r.net/wp-content/uploads/2022/06/vtr_noir.png",
                'logoSize' => 50,
                'titleText' => "Bienvenue sur le Portail Fournisseur",
                'titleSize' => 24,
                'titleColor' => "#ffffff",
                'buttonUrl' => "http://127.0.0.1:8000/",
                'buttonText' => "Accéder au portail",
                'buttonTextColor' => "#0075d5",
                'buttonBackgroundColor' => "#ffffff",
                'descriptionText' => "Bonjour et bienvenue sur le portail fournisseur de la Ville de Trois-Rivières!",
                'descriptionSize' => 10,
                'descriptionColor' => "#ffffff",
                'headerBackgroundUrl' => "https://i.ibb.co/tCcbctZ/image.png",
                'subtitleText' => "État de votre demande:",
                'subtitleSize' => 20,
                'subtitleColor' => "#5e6977",
                'iconUrl' => null,
                'iconSize' => 40,
                'importantInfoText' => "En attente",
                'importantInfoSize' => 18,
                'importantInfoColor' => "#ff8800",
                'passwordResetButtonText' => "Réinitialiser votre mot de passe",
                'passwordResetButtonColor' => "#ffffff",
                'passwordResetButtonBackgroundColor' => "#0076D5",
                'messageText' => "Un membre de notre équipe procédera à la vérification de vos informations et vous informera par courriel une fois votre demande approuvé.",
                'messageSize' => 10,
                'messageColor' => "#5e6977",
                'backgroundColor' => "#ffffff",
                'footerText' => "Merci de votre intérêt et de votre patience.<br>L'équipe de la Ville de Trois-Rivières",
                'footerSize' => 10,
                'footerColor' => "#ffffff",
                'footerBackgroundUrl' => "https://i.ibb.co/tCcbctZ/image.png",
            ],
            [
                'id' => 2,
                'name' => "Fournisseur accepté",
                'object' => "Demande accepté",
                'logoUrl' => "https://www.v3r.net/wp-content/uploads/2022/06/vtr_noir.png",
                'logoSize' => 50,
                'titleText' => "Le statut de votre demande a changé",
                'titleSize' => 24,
                'titleColor' => "#ffffff",
                'buttonUrl' => "http://127.0.0.1:8000/",
                'buttonText' => "Accéder au portail",
                'buttonTextColor' => "#0075d5",
                'buttonBackgroundColor' => "#ffffff",
                'descriptionText' => null,
                'descriptionSize' => 10,
                'descriptionColor' => "#ffffff",
                'headerBackgroundUrl' => "https://i.ibb.co/tCcbctZ/image.png",
                'subtitleText' => "État de votre demande:",
                'subtitleSize' => 20,
                'subtitleColor' => "#5e6977",
                'iconUrl' => null,
                'iconSize' => 40,
                'importantInfoText' => "Accepté",
                'importantInfoSize' => 18,
                'importantInfoColor' => "#00ca00",
                'passwordResetButtonText' => "Réinitialiser votre mot de passe",
                'passwordResetButtonColor' => "#ffffff",
                'passwordResetButtonBackgroundColor' => "#0076D5",
                'messageText' => "Vous êtes maintenant un fournisseur de la ville de Trois-Rivières!",
                'messageSize' => 10,
                'messageColor' => "#5e6977",
                'backgroundColor' => "#ffffff",
                'footerText' => "Merci de votre intérêt et de votre patience.<br>L'équipe de la Ville de Trois-Rivières",
                'footerSize' => 10,
                'footerColor' => "#ffffff",
                'footerBackgroundUrl' => "https://i.ibb.co/tCcbctZ/image.png",
            ],
            [
                'id' => 3,
                'name' => "Fournisseur refusé",
                'object' => "Demande rejeté",
                'logoUrl' => "https://www.v3r.net/wp-content/uploads/2022/06/vtr_noir.png",
                'logoSize' => 50,
                'titleText' => "Le statut de votre demande a changé",
                'titleSize' => 24,
                'titleColor' => "#ffffff",
                'buttonUrl' => "http://127.0.0.1:8000/",
                'buttonText' => "Accéder au portail",
                'buttonTextColor' => "#0075d5",
                'buttonBackgroundColor' => "#ffffff",
                'descriptionText' => null,
                'descriptionSize' => 10,
                'descriptionColor' => "#ffffff",
                'headerBackgroundUrl' => "https://i.ibb.co/tCcbctZ/image.png",
                'subtitleText' => "État de votre demande:",
                'subtitleSize' => 20,
                'subtitleColor' => "#5e6977",
                'iconUrl' => null,
                'iconSize' => 40,
                'importantInfoText' => "Refusé",
                'importantInfoSize' => 18,
                'importantInfoColor' => "#c50000",
                'passwordResetButtonText' => "Réinitialiser votre mot de passe",
                'passwordResetButtonColor' => "#ffffff",
                'passwordResetButtonBackgroundColor' => "#0076D5",
                'messageText' => "Votre demande à été refusé. Pour plus de détails, veuillez vous rendre sur le portail.",
                'messageSize' => 10,
                'messageColor' => "#5e6977",
                'backgroundColor' => "#ffffff",
                'footerText' => "Merci de votre intérêt et de votre patience.<br>L'équipe de la Ville de Trois-Rivières",
                'footerSize' => 10,
                'footerColor' => "#ffffff",
                'footerBackgroundUrl' => "https://i.ibb.co/tCcbctZ/image.png",
            ],
            [
                'id' => 4,
                'name' => "Fournisseur refusé avec raison",
                'object' => "Demande rejeté",
                'logoUrl' => "https://www.v3r.net/wp-content/uploads/2022/06/vtr_noir.png",
                'logoSize' => 50,
                'titleText' => "Le statut de votre demande a changé",
                'titleSize' => 24,
                'titleColor' => "#ffffff",
                'buttonUrl' => "http://127.0.0.1:8000/",
                'buttonText' => "Accéder au portail",
                'buttonTextColor' => "#0075d5",
                'buttonBackgroundColor' => "#ffffff",
                'descriptionText' => null,
                'descriptionSize' => 10,
                'descriptionColor' => "#ffffff",
                'headerBackgroundUrl' => "https://i.ibb.co/tCcbctZ/image.png",
                'subtitleText' => "État de votre demande:",
                'subtitleSize' => 20,
                'subtitleColor' => "#5e6977",
                'iconUrl' => null,
                'iconSize' => 40,
                'importantInfoText' => "Refusé",
                'importantInfoSize' => 18,
                'importantInfoColor' => "#c50000",
                'passwordResetButtonText' => "Réinitialiser votre mot de passe",
                'passwordResetButtonColor' => "#ffffff",
                'passwordResetButtonBackgroundColor' => "#0076D5",
                'messageText' => "Votre demande à été refusé pour la raison suivante: {{ \$reason }}. Pour plus de détails, veuillez vous rendre sur le portail.",
                'messageSize' => 10,
                'messageColor' => "#5e6977",
                'backgroundColor' => "#ffffff",
                'footerText' => "Merci de votre intérêt et de votre patience.<br>L'équipe de la Ville de Trois-Rivières",
                'footerSize' => 10,
                'footerColor' => "#ffffff",
                'footerBackgroundUrl' => "https://i.ibb.co/tCcbctZ/image.png",
            ],
            [
                'id' => 5,
                'name' => "Fournisseur en attente",
                'object' => "Demande en attente",
                'logoUrl' => "https://www.v3r.net/wp-content/uploads/2022/06/vtr_noir.png",
                'logoSize' => 50,
                'titleText' => "Le statut de votre demande a changé",
                'titleSize' => 24,
                'titleColor' => "#ffffff",
                'buttonUrl' => "http://127.0.0.1:8000/",
                'buttonText' => "Accéder au portail",
                'buttonTextColor' => "#0075d5",
                'buttonBackgroundColor' => "#ffffff",
                'descriptionText' => null,
                'descriptionSize' => 10,
                'descriptionColor' => "#ffffff",
                'headerBackgroundUrl' => "https://i.ibb.co/tCcbctZ/image.png",
                'subtitleText' => "État de votre demande:",
                'subtitleSize' => 20,
                'subtitleColor' => "#5e6977",
                'iconUrl' => null,
                'iconSize' => 40,
                'importantInfoText' => "En attente",
                'importantInfoSize' => 18,
                'importantInfoColor' => "#ff8800",
                'passwordResetButtonText' => "Réinitialiser votre mot de passe",
                'passwordResetButtonColor' => "#ffffff",
                'passwordResetButtonBackgroundColor' => "#0076D5",
                'messageText' => "Votre demande a été mise en attente par un responsable.",
                'messageSize' => 10,
                'messageColor' => "#5e6977",
                'backgroundColor' => "#ffffff",
                'footerText' => "Merci de votre intérêt et de votre patience.<br>L'équipe de la Ville de Trois-Rivières",
                'footerSize' => 10,
                'footerColor' => "#ffffff",
                'footerBackgroundUrl' => "https://i.ibb.co/tCcbctZ/image.png",
            ],
            [
                'id' => 6,
                'name' => "Réinitialisation mot de passe fournisseur",
                'object' => "Réinitialiser votre mot de passe",
                'logoUrl' => "https://www.v3r.net/wp-content/uploads/2022/06/vtr_noir.png",
                'logoSize' => 50,
                'titleText' => "Réinitialiser votre mot de passe",
                'titleSize' => 24,
                'titleColor' => "#ffffff",
                'buttonUrl' => "http://127.0.0.1:8000/",
                'buttonText' => "Accéder au portail",
                'buttonTextColor' => "#0075d5",
                'buttonBackgroundColor' => "#ffffff",
                'descriptionText' => "Nous avons reçu une demande de réinitialisation de votre mot de passe.",
                'descriptionSize' => 10,
                'descriptionColor' => "#ffffff",
                'headerBackgroundUrl' => "https://i.ibb.co/tCcbctZ/image.png",
                'subtitleText' => "Compte:",
                'subtitleSize' => 20,
                'subtitleColor' => "#5e6977",
                'iconUrl' => null,
                'iconSize' => 40,
                'importantInfoText' => "{{ \$supplier->name }}",
                'importantInfoSize' => 18,
                'importantInfoColor' => "#0076D5",
                'passwordResetButtonText' => "Réinitialiser votre mot de passe",
                'passwordResetButtonColor' => "#ffffff",
                'passwordResetButtonBackgroundColor' => "#0076D5",
                'messageText' => "Si ce n'est pas votre compte, veuillez ne pas tenir compte de ce message.",
                'messageSize' => 10,
                'messageColor' => "#5e6977",
                'backgroundColor' => "#ffffff",
                'footerText' => "Merci de votre intérêt et de votre patience.<br>L'équipe de la Ville de Trois-Rivières",
                'footerSize' => 10,
                'footerColor' => "#ffffff",
                'footerBackgroundUrl' => "https://i.ibb.co/tCcbctZ/image.png",
            ],
            [
                'id' => 7,
                'name' => "Fournisseur à réviser",
                'object' => "Demande à vérifier",
                'logoUrl' => "https://www.v3r.net/wp-content/uploads/2022/06/vtr_noir.png",
                'logoSize' => 50,
                'titleText' => "Une demande est en attente de vérification",
                'titleSize' => 24,
                'titleColor' => "#ffffff",
                'buttonUrl' => "http://127.0.0.1:8080/",
                'buttonText' => "Accéder au portail",
                'buttonTextColor' => "#0075d5",
                'buttonBackgroundColor' => "#ffffff",
                'descriptionText' => null,
                'descriptionSize' => 10,
                'descriptionColor' => "#ffffff",
                'headerBackgroundUrl' => "https://i.ibb.co/tCcbctZ/image.png",
                'subtitleText' => "Fournisseur:",
                'subtitleSize' => 20,
                'subtitleColor' => "#5e6977",
                'iconUrl' => null,
                'iconSize' => 40,
                'importantInfoText' => "{{ \$supplier->neq }}<br>{{ \$supplier->name }}",
                'importantInfoSize' => 18,
                'importantInfoColor' => "#0076D5",
                'passwordResetButtonText' => "Réinitialiser votre mot de passe",
                'passwordResetButtonColor' => "#ffffff",
                'passwordResetButtonBackgroundColor' => "#0076D5",
                'messageText' => "Pour plus de détails, consultez le portail responsable.",
                'messageSize' => 10,
                'messageColor' => "#5e6977",
                'backgroundColor' => "#ffffff",
                'footerText' => null,
                'footerSize' => 10,
                'footerColor' => "#ffffff",
                'footerBackgroundUrl' => "https://i.ibb.co/tCcbctZ/image.png",
            ],
            [
                'id' => 8,
                'name' => "Inscription fournisseur notification",
                'object' => "Nouvelle demande",
                'logoUrl' => "https://www.v3r.net/wp-content/uploads/2022/06/vtr_noir.png",
                'logoSize' => 50,
                'titleText' => "Un fournisseur à fait une nouvelle demande",
                'titleSize' => 24,
                'titleColor' => "#ffffff",
                'buttonUrl' => "http://127.0.0.1:8080/",
                'buttonText' => "Accéder au portail",
                'buttonTextColor' => "#0075d5",
                'buttonBackgroundColor' => "#ffffff",
                'descriptionText' => null,
                'descriptionSize' => 10,
                'descriptionColor' => "#ffffff",
                'headerBackgroundUrl' => "https://i.ibb.co/tCcbctZ/image.png",
                'subtitleText' => "Fournisseur:",
                'subtitleSize' => 20,
                'subtitleColor' => "#5e6977",
                'iconUrl' => null,
                'iconSize' => 40,
                'importantInfoText' => "{{ \$supplier->neq }}<br>{{ \$supplier->name }}",
                'importantInfoSize' => 18,
                'importantInfoColor' => "#0076D5",
                'passwordResetButtonText' => "Réinitialiser votre mot de passe",
                'passwordResetButtonColor' => "#ffffff",
                'passwordResetButtonBackgroundColor' => "#0076D5",
                'messageText' => "Pour plus de détails, consultez le portail responsable.",
                'messageSize' => 10,
                'messageColor' => "#5e6977",
                'backgroundColor' => "#ffffff",
                'footerText' => null,
                'footerSize' => 10,
                'footerColor' => "#ffffff",
                'footerBackgroundUrl' => "https://i.ibb.co/tCcbctZ/image.png",
            ]
        ]);
    }
}